spring:
  application:
    name: Flow
    default-staff-password: 80D6A2EC556B7E2DEC301265B7A5598C232ED4E9CAB045D4E0E8769059D002AC
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/flow?createDatabaseIfNotExist=true
    username: flow-user
    password: flow-password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 1
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 203d4c8ef4d101
    password: 0bdf510c75ca01
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  secret: 80D6A2EC556B7E2DEC301265B7A5598C232ED4E9CAB045D4E0E8769059D002AC
  expiration-time: 86400000
cors:
  origins: http://localhost:3030
work:
  startTime: "09:00"
  endTime: "17:00"
